### PR TITLE
Integrate Mayhem

### PR DESCRIPTION
**Pull request by rnshah9**

### CODE REVIEW

**Review by xansec — CHANGES_REQUESTED** [review]
Can we remove the 0d1n fuzzer? I'm not sure hardcoding a publicly accessible endpoint into a container is a great idea. Please make the requested changes.

**Comment by rnshah9** [comment]
I chose [Google Gruyere](https://google-gruyere.appspot.com/), which is supposed to be open to attack, but I agree it's still dicey.

I'm happy to remove the target, but would I then lose the points for hitting 100 test cases?

**Comment by xansec** [comment]
I don't think so, as long as the other target is able to generate 100 test cases. I am not sure that the first target was ever working as expected in the first place, as Mayhem runs targets in a sandboxed environment, so no internet connectivity is allowed for targets.

**Comment by rnshah9** [comment]
Yeah, I asked because unfortunately the other target is not generating 100 test cases. 

Interesting, I didn't realize that but it makes sense. Should I still go ahead and remove it?

**Review by xansec — COMMENTED** [review]
Yeah, I'm seeing 104 as the max for this project anyways.

**Review by xansec — APPROVED** [review]
LGTM!

**Pull request merged**
